# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2C2D)
$foreground = rgb(E1DFDB)
$color0 = rgb(4F5152)
$color1 = rgb(5C605D)
$color2 = rgb(7F7A73)
$color3 = rgb(7F7A73)
$color4 = rgb(7F7A73)
$color5 = rgb(7F7A73)
$color6 = rgb(7F7A73)
$color7 = rgb(CCC9C4)
$color8 = rgb(8E8C89)
$color9 = rgb(7A807C)
$color10 = rgb(A9A399)
$color11 = rgb(A9A399)
$color12 = rgb(A9A399)
$color13 = rgb(A9A399)
$color14 = rgb(A9A399)
$color15 = rgb(CCC9C4)
