# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(272A2D)
$foreground = rgb(E8DFD9)
$color0 = rgb(4C4F53)
$color1 = rgb(14202C)
$color2 = rgb(14202C)
$color3 = rgb(2F3A41)
$color4 = rgb(505657)
$color5 = rgb(505657)
$color6 = rgb(8D7B6E)
$color7 = rgb(D5C9C1)
$color8 = rgb(958D87)
$color9 = rgb(1A2B3B)
$color10 = rgb(1A2B3B)
$color11 = rgb(3E4D57)
$color12 = rgb(6A7274)
$color13 = rgb(6A7274)
$color14 = rgb(BCA493)
$color15 = rgb(D5C9C1)
